
matrix:
  fast_finish: true
  sudo: true
  include:
    - language: c
      script:
        - Å›udo make all install
    - language: c
      script:
        - sudo make COVERAGE="-g -coverage -DBFI_NOCHECKS -O0" all install test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
  cache: apt
